### ISSUE TITLE
What's the difference of access control mechanism between bcos 2.0 and bcos 3.0?

### ISSUE THREAD

**Issue by JangoCCC** [FISCO-BCOS/bcos-auth#16]
I see the console supports `grantNodeManager` command in 2.x version, however, I don't see this command in v3.0 console. When I dig ino the source code, I find the precompiled contracts PermissionPrecompiled.sol & PermissionPrecompiled.cpp implement the command above. And v3.0 doesn't have the PermissionPrecompiled contract. Recently I'm doing some development based on V3.0, and I want to control the access of commands like `addSealer`. Any ideas on this?

**Comment by kyonRay** [comment]
Hi @JangoCCC ,

ACL between FISCO BCOS 2.x and 3.x is quite different. Please check this page: [link](https://fisco-bcos-doc.readthedocs.io/zh_CN/latest/docs/develop/committee_usage.html) for further research.

You can check out `FISCO BCOS` and `console` in `v3.0-rc4` version, and you will find new console commands about consensus node ACL proposals :)

**Comment by kyonRay** [comment]
You can check out this PR #19 :)

**Comment by JangoCCC** [comment]
Just found out that you guys released rc4, this version solved my problem, thanks!
